steps:
  # 1️⃣ Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/share-content'
      - '.'

  # 2️⃣ Push Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/share-content'

  # 3️⃣ Deploy to Cloud Run with runtime secrets
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'share-content'
      - '--image'
      - 'gcr.io/$PROJECT_ID/share-content'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--service-account'
      - '416309094312-compute@developer.gserviceaccount.com'
      - '--update-secrets'
      - 'DOMAIN=DOMAIN:latest,MONGO_URL=MONGO_URL:latest,REDIS_URL=REDIS_URL:latest,TOKEN_SECRET=TOKEN_SECRET:latest'

images:
  - 'gcr.io/$PROJECT_ID/share-content'
