steps:
  # 1. Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_SERVICE}:${COMMIT_SHA}'
      - '.'

  # 2. Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_SERVICE}:${COMMIT_SHA}'

  # 3. Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy ${_SERVICE} \
          --image ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_SERVICE}:${COMMIT_SHA} \
          --platform managed \
          --region ${_REGION} \
          --allow-unauthenticated \
          --set-secrets "DOMAIN=projects/${PROJECT_ID}/secrets/DOMAIN:latest" \
          --set-secrets "MONGO_URL=projects/${PROJECT_ID}/secrets/MONGO_URL:latest" \
          --set-secrets "REDIS_URL=projects/${PROJECT_ID}/secrets/REDIS_URL:latest" \
          --set-secrets "TOKEN_SECRET=projects/${PROJECT_ID}/secrets/TOKEN_SECRET:latest"

substitutions:
  _REGION: us-central1
  _REPO: share-content
  _SERVICE: share-content

images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_SERVICE}:${COMMIT_SHA}'
