services:
  web:
    build:
      context: .
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      MONGO_URL: mongodb+srv://nikhilsingh95969:HxOuijpPRVSRYoin@cluster0.3vv7fgd.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      REDIS_URL: rediss://default:AYwhAAIncDExNjEwM2NiZThmNmQ0ODA5ODk4MjM2NGU5YjIyZDhmOHAxMzU4NzM@polished-redfish-35873.upstash.io:6379
      TOKEN_SECRET: local-secret
